version: '3.8'

services:
  mysql_database:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=DuAnTotNghiep
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mysql_container -u root -p123456 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - my_app_network

  spring_boot_project:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQLDB_HOST=mysql_container
      - MYSQLDB_CONTAINER_PORT=3306
      - MYSQLDB_DB_NAME=DuAnTotNghiep
      - DB_USER=root
      - DB_PASSWORD=123456
    depends_on:
      mysql_database:
        condition: service_healthy
    restart: always
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge
