# version: '3.8'

# services:
#   # mysql_database:
#   #   image: mysql:8
#   #   command: --max_allowed_packet=1024000000
#   #   container_name: mysql_container
#   #   environment:
#   #     MYSQL_ROOT_PASSWORD: 123456
#   #     MYSQL_DATABASE: DuAnTotNghiep
#   #     MYSQL_USER: root
#   #     MYSQL_PASSWORD: 123456
#   #   volumes:
#   #     - database_volumes:/var/lib/mysql
#   #   healthcheck:
#   #     test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
#   #     interval: 1s
#   #     timeout: 20s
#   #     retries: 10
#   #     start_period: 10s
#   #   networks:
#   #     - my_app_network

#   mysql_database:
#     image: mysql:latest
#     container_name: mysql_container
#     environment:
#       MYSQL_ROOT_PASSWORD: 123456
#       MYSQL_DATABASE: DuAnTotNghiep
#       MYSQL_USER: root
#     ports:
#       - "3307:3306"
#     healthcheck:
#       test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD
#       interval: 1s
#       timeout: 20s
#       retries: 10
#       start_period: 10s
#     restart: always
#     networks:
#       - my_app_network

#   spring_boot_project:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "9090:8080"
#     environment:
#       - MYSQLDB_HOST=mysql_container
#       - MYSQLDB_CONTAINER_PORT=3306
#       - MYSQLDB_DB_NAME=DuAnTotNghiep
#       - DB_USER=root
#       - DB_PASSWORD=123456
#     depends_on:
#       mysql_database:
#         condition: service_healthy
#     restart: always
#     networks:
#       - my_app_network

# networks:
#   my_app_network:
#     driver: bridge
  version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
    volumes:
      # - .mysql/storage/mysql:/logs
      - ./db:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
        - dev

  server:
    build:
      context: DATN_FiveStus
      dockerfile: Dockerfile
    image: datn_five_stus:0.0.3
    depends_on:
      - db
    networks:
      - dev
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Aa123456
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 3310
      DATABASE_DDL: update
    restart: on-failure
networks:
  dev:
    driver: bridge
volumes:
  db:
    driver: local